
ALTER TABLE public.projects
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS budget_total NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS budget_spent NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS start_date DATE,
  ADD COLUMN IF NOT EXISTS expected_end_date DATE,
  ADD COLUMN IF NOT EXISTS project_manager_id UUID;
